ballerina-platform/module-ballerina-soap

component/pom.xml
component/src/main/assembly/dist.xml
component/src/main/ballerina/ballerina/net/soap/natives.bal
component/src/main/java/connectors/ConnectorExtensionPackageRepositoryProvider.java
pom.xml

This is the Intial commit
This adds the component structure and the proposed design
The design
enum SoapVersion {
SOAP11, SOAP12
}
public struct  Request {
xml[] headers;
xml payload;
string soapAction;
string from;
string to;
string replyTo;
string faultTo;
string messageId;
string relatesTo;
string username;
string password;
}
public struct Response {
xml[] headers;
xml payload;
string from;
string to;
string replyTo;
string faultTo;
string messageId;
string relatesTo;
}
public struct SoapError {
string msg;
error cause;
StackFrame[] stackTrace;
int errorCode;
}
public connector SoapClient () {
action sendRobust(Request request, string endpointURL) (SoapError) {
return null;
}
action fireAndForget(Request request, string endpointURL) {
}
action sendReceive(Request request, string …

Add SOAP Client Connector [WIP]

---

Ballerina.toml
soap/Package.md
soap/soap_connector.bal
soap/tests/test.bal

- Update the code with missed functionality
- Add config files required for ballerina central

Update the code with missed functionality

---

Ballerina.toml
README.md
soap/Package.md
soap/soap_connector.bal
soap/soap_endpoint.bal
soap/soap_utils.bal

Fix for latest syntax changes

---

README.md
soap/Package.md

Update markdown files

---

soap/soap_connector.bal
soap/soap_endpoint.bal
soap/soap_types.bal

This PR fixes syntax issues in the guide.

Fix syntax issues

---

Ballerina.toml
README.md
soap/Package.md

Update markdown files and toml file for 0.980.0 release

Prepare connector for Ballerina 0.980.0 release

---

.travis.yml
Ballerina.toml
README.md
soap/Package.md

> Update SOAP connector for 0.981.0 stable release

Update for 0.981.0 release

---

Ballerina.toml
README.md
soap/Package.md
soap/soap_connector.bal
soap/soap_endpoint.bal
soap/soap_types.bal
soap/soap_utils.bal

- Update SOAP connector for 0.981.0 stable release
- Fix documentation syntaxes
- Update markdown files

Update for 0.982.0 release

---

Ballerina.toml

- Update package version into 0.3.11 for the compatibility of Ballerina Central
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/10619

Update package version

---

.gitignore
.travis.yml
Ballerina.toml
README.md
soap/Module.md
soap/soap_connector.bal
soap/soap_constants.bal
soap/soap_endpoint.bal
soap/soap_types.bal
soap/soap_utils.bal
soap/tests/test.bal

- Update connector for Ballerina 0.983.0 release

Update for 0.983.0 release

---

Ballerina.toml
README.md
soap/Module.md
soap/soap_connector.bal
soap/soap_constants.bal
soap/soap_endpoint.bal
soap/soap_types.bal
soap/soap_utils.bal
soap/tests/test.bal

- Fix for latest syntax changes
- Refactor code

Fix connector for Ballerina 0.990.0

---

Ballerina.toml
soap/soap_constants.bal

- Fix SOAP error code
- Update toml version in order to match with Ballerina Central

Fix for PR reviews

---

Ballerina.toml
README.md
soap/Module.md
soap/soap_utils.bal

Sync with ballerina 0.990.4

---

Ballerina.toml
README.md
soap/Module.md

Update Readme and toml files

---

README.md
soap/Module.md

Update the ballerina version in Readme

---

soap/soap11_endpoint.bal
soap/soap12_endpoint.bal
soap/soap_types.bal
soap/soap_utils.bal
soap/tests/testSoap11.bal
soap/tests/testSoap12.bal

Fixes the following issues
https://github.com/wso2-ballerina/module-soap/issues/51
https://github.com/wso2-ballerina/module-soap/issues/46
https://github.com/wso2-ballerina/module-soap/issues/47
https://github.com/wso2-ballerina/module-soap/issues/48
https://github.com/wso2-ballerina/module-soap/issues/49

Refactor the soap module

---

soap/soap11_endpoint.bal
soap/soap12_endpoint.bal
soap/soap_utils.bal

$subject.
Fix issue: https://github.com/ballerina-platform/ballerina-lang/issues/3415

Add soap attachment support

---

soap/Module.md
soap/soap11_endpoint.bal
soap/soap12_endpoint.bal
soap/soap_constants.bal
soap/soap_types.bal
soap/soap_utils.bal

This is the doc review of the SOAP module content. 
Fixes https://github.com/wso2-ballerina/module-soap/issues/44
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the …

Review the SOAP module content

---

.gitignore
.travis.yml
Ballerina.lock
Ballerina.toml
README.md
src/soap/Module.md
src/soap/soap11_endpoint.bal
src/soap/soap12_endpoint.bal
src/soap/soap_constants.bal
src/soap/soap_types.bal
src/soap/soap_utils.bal
src/soap/tests/testSoap11.bal
src/soap/tests/testSoap12.bal

> Refactor code and and project code structure of the connector for Ballerina 1.0.0-RC1

Refactor connector code for ballerina 1.0.0

---

Ballerina.toml

> Bump connector version to 0.4.0

Bump connector version to 0.4.0

---

Ballerina.lock
README.md
src/soap/Module.md
src/soap/soap_utils.bal

> Fix ReadME.md and util class

Fix issues in util class and readme.md

---

src/soap/soap11_endpoint.bal
src/soap/tests/testSoap11.bal

Fix issue 65 by swapping arguments

---

Ballerina.lock
Ballerina.toml

Increment version for new release.

---

.travis.yml
Ballerina.lock
Ballerina.toml
README.md
src/soap/Module.md

> Migrate the Soap Connector from Ballerina version 1.0.1 to 1.1.0.

Migrate the Ballerina version to 1.1.0

---

.github/workflows/ci.yml
.github/workflows/release.yml
.travis.yml
Ballerina.lock
Ballerina.toml
README.md
src/soap/Module.md
src/soap/soap_constants.bal
src/soap/soap_utils.bal

Migrate to Ballerina 1.2.0 and change org name

---

.github/workflows/release.yml

Change the release type in ci.yml

---

Ballerina.lock
Ballerina.toml
README.md
src/soap/Module.md
src/soap/soap11_endpoint.bal
src/soap/soap12_endpoint.bal
src/soap/soap_utils.bal

Changed the order of function parameters to maintain consistency. 
Fixes: https://github.com/ballerina-platform/module-ballerina-soap/issues/72 and https://github.com/ballerina-platform/module-ballerina-soap/issues/68

Change the order of function parameters and fix bugs

---

.travis.yml
Ballerina.lock
Ballerina.toml
README.md
src/soap/Module.md
src/soap/soap11_endpoint.bal
src/soap/soap12_endpoint.bal
src/soap/soap_utils.bal
src/soap/tests/testSoap11.bal
src/soap/tests/testSoap12.bal

Migrate soap module to swan lake preview 1

---

.github/workflows/ci.yml
.github/workflows/release.yml

Change the branch from master to swan lake in github workflows

---

README.md
src/soap/Module.md

Fixes: https://github.com/ballerina-platform/module-ballerina-soap/issues/77

Update soap connector documentation

---

.github/workflows/build-timestamped-master.yml
.github/workflows/publish-release.yml
.github/workflows/update_specs.yml
README.md
changelog.md

Update README and github workflows

---

.github/workflows/build-with-bal-test-native.yml

Fix GraalVM Check workflow file

---

ballerina/Dependencies.toml
ballerina/soap.bal
ballerina/tests/basic_client_test.bal

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/4727

Add soap action to `sendReceive` and `sendOnly` functons

---

ballerina/Dependencies.toml
ballerina/soap.bal
ballerina/soap_utils.bal
ballerina/tests/basic_client_test.bal

Refactor soap module

---

ballerina/soap.bal
ballerina/soap_utils.bal
ballerina/tests/basic_client_test.bal

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/4728

Add header map to sendReceive and sendOnly functons

---

ballerina/Dependencies.toml
gradle.properties

Sync release 0.2.0 with 7.x

---

.github/workflows/build-timestamped-master.yml
.github/workflows/publish-release.yml
.github/workflows/update_specs.yml
ballerina/Dependencies.toml

Change branch name `main` to `2201.7.x` in github workflow files

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
ballerina/build.gradle
gradle.properties

Update the module version to 0.8.0

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
gradle.properties

Update Gradle plugin to 2.2.2

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Bump dependency versions for update 9

---

.github/workflows/build-timestamped-master.yml
.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml

Fix library repository link in workflow files

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
ballerina/Module.md
ballerina/Package.md
ballerina/configs.bal
ballerina/modules/soap11/Module.md
ballerina/modules/soap11/soap11.bal
ballerina/modules/soap12/Module.md
ballerina/modules/soap12/soap12.bal
ballerina/soap_utils.bal
ballerina/types.bal
gradle.properties

Set security configuration types to public

---

ballerina/Dependencies.toml
ballerina/modules/soap11/tests/http_secured_service.bal
ballerina/modules/soap11/tests/http_soap_service.bal
ballerina/modules/soap11/tests/soap11_client_test.bal
ballerina/modules/soap12/tests/http_secured_service.bal
ballerina/modules/soap12/tests/http_soap_service.bal
ballerina/modules/soap12/tests/soap12_client_test.bal

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6428

Fix intermittent errors in test cases

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
ballerina/error.bal
ballerina/modules/soap11/error.bal
ballerina/modules/soap11/soap11.bal
ballerina/modules/soap11/tests/http_soap_service.bal
ballerina/modules/soap11/tests/soap11_client_test.bal
ballerina/modules/soap12/error.bal
ballerina/modules/soap12/soap12.bal
ballerina/modules/soap12/tests/http_soap_service.bal
ballerina/modules/soap12/tests/soap12_client_test.bal
ballerina/modules/wssec/signature.bal
ballerina/modules/wssec/ws_security_methods.bal
ballerina/soap_utils.bal

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6688

Improve error handling in the SOAP Module

---

ballerina/Dependencies.toml
gradle.properties

Update library versions for 2201.10.0

---

build-config/resources/Ballerina.toml
build.gradle
gradle.properties

$Subject
Due to https://github.com/ballerina-platform/ballerina-library/issues/7012

[master] Update http version

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
ballerina/modules/soap11/tests/soap11_client_test.bal
ballerina/modules/soap12/tests/soap12_client_test.bal
ballerina/soap_utils.bal
build-config/resources/Ballerina.toml
build.gradle
gradle.properties
native/src/main/java/io/ballerina/lib/soap/Soap.java

Migrate to new Runtime APIs

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
gradle.properties

Update library timestamp versions
